# Generated by Django 5.0.4 on 2024-04-20 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0004_alter_datasabertas_user'),
        ('paciente', '0002_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='data_aberta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medico.datasabertas'),
        ),
    ]
