# Generated by Django 5.0.4 on 2024-04-20 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0003_alter_consulta_data_aberta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='consulta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.consulta'),
        ),
        migrations.CreateModel(
            name='Avaliacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(max_length=250)),
                ('avaliacao', models.CharField(choices=[('M', 'Muito Ruim'), ('R', 'Ruim'), ('S', 'Regular'), ('B', 'Bom'), ('E', 'Excelente')], default='', max_length=1)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.consulta')),
            ],
        ),
    ]
