# Generated by Django 5.0.4 on 2024-04-20 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0005_alter_avaliacoes_avaliacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacoes',
            name='avaliacao',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
    ]
