# Generated by Django 5.0.4 on 2024-04-25 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0005_alter_datasabertas_user'),
        ('paciente', '0009_alter_consulta_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacoes',
            name='consulta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='paciente.consulta'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='data_aberta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='medico.datasabertas'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='consulta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='paciente.consulta'),
        ),
    ]
